#!/usr/bin/bash
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Generate USB image from iso

USB_SIZE=700m

if [ $# != "4" ] ; then
	echo "usbgen path_to_iso_file path_to_usb_image listusb_path tmpdir"
	exit 1
fi

ISO_FILE=$1
TMPDIR=$4
ISO_PATH=$TMPDIR/iso

USB_FILE=$2
USB_PATH=$TMPDIR/usb

[ -d $ISO_PATH ] || mkdir -p $ISO_PATH
[ -d $USB_PATH ] || mkdir -p $USB_PATH

# Mount up the ISO image
isodev=`lofiadm -a $ISO_FILE` || exit
mount -F hsfs $isodev $ISO_PATH

mkfile -n $USB_SIZE $USB_FILE
devs=`lofiadm -a $USB_FILE`
rdevs=`echo $devs|sed -e 's/lofi/rlofi/'`

yes | newfs $rdevs || exit
mount -o nologging $devs $USB_PATH || exit

# Copy ISO contents to USB
echo "Copying ISO contents to USB image"
cd $ISO_PATH
find . -print|cpio -pmudV $USB_PATH

# Remove GRUB entries which apply only to DVD
sed -e '/tracing/,$d' $USB_PATH/boot/grub/menu.lst > $USB_PATH/boot/grub/menu2.lst
rm $USB_PATH/boot/grub/menu.lst
mv $USB_PATH/boot/grub/menu2.lst $USB_PATH/boot/grub/menu.lst

# Now mount microroot and make required changes for USB
echo "Creating temporary microroot"
cp $ISO_PATH/boot/x86.microroot $TMPDIR/x86.microroot.gz

cd $TMPDIR
gunzip $TMPDIR/x86.microroot.gz
TMP_MICROROOT=$TMPDIR/microroot
[ -d $TMP_MICROROOT ] || mkdir $TMP_MICROROOT
mount -F ufs -o nologging `lofiadm -a $TMPDIR/x86.microroot` $TMP_MICROROOT

# Creating the new microroot for USB
echo "Replacing USB specific files"
cd $TMP_MICROROOT
touch $TMP_MICROROOT/.liveusb
[ -d $TMP_MICROROOT/sbin ] || mkdir $TMP_MICROROOT/sbin/

cd $TMPDIR
umount $TMP_MICROROOT
gzip -9 $TMPDIR/x86.microroot

echo "Copying microroot to USB"
rm $USB_PATH/boot/x86.microroot
cp $TMPDIR/x86.microroot.gz $USB_PATH/boot/x86.microroot

# unmounting, and uninstalling the lofi'ed devices
echo "Cleaning up."
umount $USB_PATH
umount $ISO_PATH
lofiadm -d $TMPDIR/x86.microroot
lofiadm $devs >/dev/null 2>&1 && lofiadm -d $devs
lofiadm -d $isodev

echo "=== $0 completed at `date`"
