#
# This file and all modifications and additions to the pristine
# package are under the same license as the package itself.

%include Solaris.inc

%ifarch amd64 sparcv9
%include arch64.inc
%endif

%include base.inc

Name:                SFEloudmouth
Summary:             XMPP/Jabber C programming library
Version:             1.4.3
License:             LGPLv2+
Group:               System Environment/Libraries
Source:              http://ftp.imendio.com/pub/imendio/loudmouth/src/loudmouth-%{version}.tar.bz2
Source1:             libidn.pc.64
Source2:             libidn.pc

URL:                 http://www.loudmouth-project.org/
Patch1:              loudmouth-01-certs_location.diff
Patch2:              loudmouth-02-async_assertion.diff
Patch3:              loudmouth-03-fix-sasl-md5-digest-uri.diff

SUNW_BaseDir:        %{_basedir}
#SUNW_Copyright:      %{name}.copyright
BuildRoot:           %{_tmppath}/%{name}-%{version}-build
%include default-depend.inc
Requires:            SUNWglib2
Requires:            SUNWgnu-idn
Requires:            SFElibasyncns
Requires:            SUNWgnutls
BuildRequires:       SUNWglib2-devel
BuildRequires:       SUNWgnu-idn
BuildRequires:       SFElibasyncns-devel
BuildRequires:       SUNWgnutls-devel

%description
Loudmouth is a lightweight and easy-to-use C library for programming
with the XMPP/Jabber protocol. It's designed to be easy to get started
with and yet extensible to let you do anything the XMPP protocol allows.

%package devel
Summary:                 %{summary} - development files
SUNW_BaseDir:            %{_prefix}
%include default-depend.inc
Requires: %name

%prep
%setup -q -c -n %name-%version
cd loudmouth-%version
%patch1 -p1
%patch2 -p1
%patch3 -p1
cd ..

%ifarch amd64 sparcv9
cp -rp loudmouth-%version loudmouth-%{version}-64
%endif


%build
%ifarch amd64 sparcv9
cd loudmouth-%{version}-64

export CFLAGS="%optflags64"
export CXXFLAGS="%cxx_optflags64"
export CPPFLAGS="-Du_int64_t=uint64_t -Du_int32_t=uint32_t -Du_int16_t=uint16_t -Du_int8_t=uint8_t"
export LDFLAGS="%_ldflags64 %{gnu_lib_path64} -lstdc++"

cp %{SOURCE1} ./libidn.pc
export PKG_CONFIG_PATH=`pwd`:%{_libdir}/%{_arch64}/pkgconfig

./configure --prefix=%{_prefix} \
            --bindir=%{_bindir}/%{_arch64} \
            --libdir=%{_libdir}/%{_arch64} \
            --sysconfdir=%{_sysconfdir} \
            --datadir=%{_datadir} \
            --includedir=%{_includedir} \
            --mandir=%{_mandir} \
            --enable-static=no \
            --with-asyncns=yes \
            --with-ssl=gnutls

gmake
cd ..
%endif

cd loudmouth-%{version}
export CFLAGS="%optflags"
export CXXFLAGS="%cxx_optflags"
export CPPFLAGS="-Du_int64_t=uint64_t -Du_int32_t=uint32_t -Du_int16_t=uint16_t -Du_int8_t=uint8_t"
export LDFLAGS="%_ldflags %{gnu_lib_path} -lstdc++"

cp %{SOURCE2} ./libidn.pc
export PKG_CONFIG_PATH=`pwd`:%{_libdir}/pkgconfig

./configure --prefix=%{_prefix} \
            --bindir=%{_bindir} \
            --libdir=%{_libdir} \
            --sysconfdir=%{_sysconfdir} \
            --datadir=%{_datadir} \
            --includedir=%{_includedir} \
            --mandir=%{_mandir} \
            --enable-static=no \
            --with-asyncns=yes \
            --with-ssl=gnutls

gmake
cd ..


%install
rm -rf $RPM_BUILD_ROOT

%ifarch amd64 sparcv9
cd loudmouth-%{version}-64

gmake install DESTDIR=$RPM_BUILD_ROOT
cd ..
%endif

cd loudmouth-%{version}
gmake install DESTDIR=$RPM_BUILD_ROOT
find $RPM_BUILD_ROOT -name '*.la' | xargs rm -f

# Copy the files from the tarball to avoid the IDs generated by gtk-doc being
# different on different builds
mkdir -p $RPM_BUILD_ROOT%{_datadir}/gtk-doc/html/%{name}/
cp -a docs/reference/html/* $RPM_BUILD_ROOT%{_datadir}/gtk-doc/html/%{name}/
cd ..

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr (-, root, bin)
%dir %attr (0755, root, bin) %{_libdir}
%{_libdir}/lib*.so*

%ifarch amd64 sparcv9
%dir %attr (0755, root, bin) %{_libdir}/%{_arch64}
%{_libdir}/%{_arch64}/lib*.so*
%endif

%files devel
%defattr (-, root, bin)
%dir %attr (0755, root, bin) %{_includedir}
%{_includedir}/*
%dir %attr (0755, root, sys) %{_datadir}
%dir %attr (0755, root, bin) %{_datadir}/gtk-doc
%{_datadir}/gtk-doc/*
%dir %attr (0755, root, other) %{_libdir}/pkgconfig
%{_libdir}/pkgconfig/*

%ifarch amd64 sparcv9
%dir %attr (0755, root, other) %{_libdir}/%{_arch64}/pkgconfig
%{_libdir}/%{_arch64}/pkgconfig/*
%endif

%changelog
* Sat Aug 29 2009 - Moinak Ghosh <moinakg<at>belenix(dot)org>
- Initial version.
