#!/bin/sh

. ./versions

cd nss-${nss_ver}/mozilla/security/nss/
USE_64=1 NSPR_LIB_DIR=/usr/lib/mps/amd64 gmake build_coreconf build_dbm all
NSPR_LIB_DIR=/usr/lib/mps gmake build_coreconf build_dbm all
USE_64=1 NSPR_LIB_DIR=/usr/lib/mps/amd64 gmake package

