#!/bin/sh

OUTPUT=/tmp/postrun.output.$$

# This executes all the postinstall scripts in the current directory.
cd /postrun_scripts

# Find out how many scripts are there
num_scripts=`ls *postinstall*|wc -l|sed 's/^ *//g`
num=1

while [ $num -le $num_scripts ] ; do

        exec_name=`echo *.$num`
        echo "Executing $exec_name"
	/bin/sh $exec_name > $OUTPUT 2>& 1
        if [ "$?" != "0" ] ; then
                echo "$exec_name failed"
		cat $OUTPUT
        fi
        num=`/bin/expr $num + 1`
	/bin/rm -f $OUTPUT
done
