#!/bin/sh
#
#  LIVECD KDE STARTUP SCRIPT ( KDE-3.5.1 )
#

dtype=$1
. /etc/default/init

if [ -z "$HOME" ]
then
	HOME=/root
	export HOME
fi

. /etc/profile.d/*.sh

if [ ! -f /.prtconf ]
then
        /usr/sbin/prtconf -pv > /.prtconf
fi
mem=`cat /.prtconf | grep "Memory size" | cut -f3 -d" "`

if [ $mem -le "256" ]
then
        /sbin/pagein `cat /etc/profile.d/kde.minimal.pagein`
else
        /sbin/pagein `cat /etc/profile.d/kde.pagein`
fi

if [ "$dtype" = "compiz" ]
then
	exec /usr/bin/ctrun -i none -l child /usr/X11/bin/xinit /usr/bin/kde-compiz
else
	exec /usr/bin/ctrun -i none -l child /usr/X11/bin/xinit /usr/bin/startkde
fi

