#!/usr/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Author: Moinak.Ghosh@Sun.COM

if [ "$1" = "-help" -o "$1" = "--help" ]
then
	echo "Usage: $0 [xfce | xfce-compiz | kde | kde-compiz]"
	echo ""
	exit 0
fi

svcadm disable application/xserver

if [ ! -z "$1" ]
then
	name=$1
	name=`echo $name | tr "[A-Z]" "[a-z]"`

	if [ "$name" = "xfce" ]
	then
		echo "1" > /.desk

	elif [ "$name" = "kde" ]
	then
		echo "2" > /.desk

	elif [ "$name" = "xfce-compiz" ]
	then
		echo "3" > /.desk

	elif [ "$name" = "kde-compiz" ]
	then
		echo "4" > /.desk
	else
		echo "The desktop $name is not present in this LiveCD"
	fi
fi

svcadm enable application/xserver

