#!/bin/sh

# Retrieve Sweet Home 3D directory
PROGRAM=@prog@
PROGRAM_DIR=@progdir@

# Run Sweet Home 3D
exec @bindir@/java -classpath "$PROGRAM_DIR"/lib/SweetHome3D.jar:"$PROGRAM_DIR"/lib/Furniture.jar:"$PROGRAM_DIR"/lib/Textures.jar:"$PROGRAM_DIR"/lib/Help.jar:"$PROGRAM_DIR"/lib/Loader3DS1_2u.jar:"$PROGRAM_DIR"/lib/iText-2.1.5.jar:"$PROGRAM_DIR"/lib/freehep-vectorgraphics-svg-2.1.1.jar:"$PROGRAM_DIR"/lib/sunflow-0.07.3b.jar:"$PROGRAM_DIR"/lib/j3dcore.jar:"$PROGRAM_DIR"/lib/j3dutils.jar:"$PROGRAM_DIR"/lib/vecmath.jar:/usr/java/jre/lib/javaws.jar -Djava.library.path="$PROGRAM_DIR"/lib -Xmx1024m com.eteks.sweethome3d.SweetHome3D -open $1
