#!/bin/ksh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Since IPS does not support postinstall scripts anymore, all the
# post install processing done by GNOME packages via postrun can not
# be done.  To workaround that problem until it is resolved, the hack
# is to extract all the postinstall scripts from all the packages that
# invokes postrun, and execute them manually.
#
# This script provides an easy way to extract all the postinstall scripts
# from SVR4 packages that contain postrun calls.  These scripts will
# be placed into a directory, along with the script that invokes them.
#
# All the files in the src/postrun_scripts directory is generated using
# this script.
#


if [ $# != 3 ] ; then
	echo "$0: svr4_pkg_list svr4_pkg_pool dst_dir"
fi

svr4_pool=$2
dst=$3
num=1

if [ ! -d $dst ] ; then
	mkdir -p $dst
fi

cat $1 | \
while read line ; do
	myfile=$svr4_pool/$line/install/postinstall
	if [ -f $myfile ] ; then
		grep -il postrun $myfile > /dev/null 2>& 1
		if [ "$?" = "0" ] ; then
			ff=$dst/$line.postinstall.$num
			cp $myfile $ff.1
			# Change "( echo" into "echo"
			sed 's/^( echo/echo/g' $ff.1 > $ff.2
			# Remove any trailing ") | \"
			sed 's/) | \\$//g' $ff.2 | grep -v BASEDIR > $ff.3
			/bin/sh $ff.3 > $ff
			/bin/rm $ff.1 $ff.2 $ff.3
			num=`expr $num + 1`
		fi 
	fi
	
done

cat << \EXEC_SCRIPT > $dst/exec_postrun
#!/bin/sh

OUTPUT=/tmp/postrun.output.$$

# This executes all the postinstall scripts in the current directory.
cd /postrun_scripts

# Find out how many scripts are there
num_scripts=`ls *postinstall*|wc -l|sed 's/^ *//g`
num=1

while [ $num -le $num_scripts ] ; do

        exec_name=`echo *.$num`
        echo "Executing $exec_name"
        /bin/sh $exec_name > $OUTPUT 2>& 1
        if [ "$?" != "0" ] ; then
                echo "$exec_name failed"
		cat $OUTPUT
        fi
        num=`/bin/expr $num + 1`
	/bin/rm -f $OUTPUT
done
EXEC_SCRIPT
