#!/usr/bin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2008 Moinak Ghosh moinakg@gmail.com
#
# Initial attempt at a script to generate i18n/g11n packages.
#

(
PKGMAPS=../../g11n/pkgmaps
PKGPREFIX=SUNW
PROTODIR=../../g11n/proto/i386/fileroot

if [ -d ${PROTODIR}/openwin ]
then
	[ -d ${PROTODIR}/openwin/lib/X11/fonts] && mv ${PROTODIR}/openwin/lib/X11/fonts ${PROTODIR}/X11/lib/X11/fonts
	[ -d ${PROTODIR}/openwin/share ] && mv ${PROTODIR}/openwin/share ${PROTODIR}/X11/share
	rm -rf ${PROTODIR}/openwin
fi

if [ -d ${PROTODIR}/usr/openwin ]
then
	mv ${PROTODIR}/usr/openwin ${PROTODIR}/usr/X11
fi

if [ ! -d ${PROTODIR}/X11/lib/locale ]
then
	(cd ${PROTODIR}/usr/X11/lib/; tar cpf - locale) | (cd ${PROTODIR}/X11/lib/; tar xpf -)
fi

if [ ! -d ${PROTODIR}/bin ]
then
	(cd ${PROTODIR}/usr/; tar cpf - bin) | (cd ${PROTODIR}/; tar xpf -)
fi

echo "/usr/X11/lib/locale/iso_8859_15/X11/fonts/TrueType" > ${PROTODIR}/usr/X11/lib/locale/iso8859-15/OWfontpath
echo "/usr/X11/lib/locale/iso_8859_2/X11/fonts/TrueType" > ${PROTODIR}/usr/X11/lib/locale/iso8859-2/OWfontpath

cp legal.xml.fsexam ${PROTODIR}/share/gnome/help/fsexam/C/legal.xml

if [ ! -f $SRC/src/cmd/.built ]
then
	cp build_fsexam $SRC/src/cmd
	PATCH1=`pwd`/Makefile.cmd.diff
	(cd $SRC/src/cmd; gpatch -p0 < $PATCH1)
	(cd $SRC/src/cmd/fsexam; sh ../build_fsexam)
	touch $SRC/src/cmd/.built
fi

fcnt=0
rm -f failed
isusr=1
isextra=1

for proto in `ls ${PKGMAPS} | egrep -v 'Makefile|i386|sparc$'`
do
	echo $proto | grep "extra$" > /dev/null
	isextra=$?

	cat ${PKGMAPS}/$proto | sed 's/openwin/X11/g' | egrep -v "app-defaults/Admin|app-defaults/Olwm|OpenWindows.fs|xview/defaults" > ${proto}_com
	pkgname=`echo $proto | cut -f2 -d"."`
	egrep " X11/| share/| bin/| lib/" ${proto}_com > /dev/null
	isusr=$?

	if [ -f ${PKGMAPS}/${proto}.i386 ]
	then
		cat ${PKGMAPS}/${proto}.i386 | sed 's/openwin/X11/g' | egrep -v "app-defaults/Admin|app-defaults/Olwm|OpenWindows.fs|xview/defaults" > ${proto}
		echo "!include ${proto}_com" >> ${proto}
	else
		mv ${proto}_com ${proto}
	fi

	if [ $isusr -ne 0 ]
	then
		egrep " X11/|share/| bin/| lib/" ${proto} > /dev/null
		isusr=$?
	fi

	BDIR="/"
	[ $isusr -eq 0 ] && BDIR="/usr"

	echo "P SUNWlang-common Localization common files" > depend
	[ $isextra -eq 0 ] && echo "P SUNWlang-common-extra Localization common files" >> depend

	cat > pkginfo << __EOF__
CLASSES=none
BASEDIR=$BDIR
TZ=PST
PATH=/sbin:/usr/sbin:/usr/bin:/usr/sadm/install/bin
PKG=${PKGPREFIX}${pkgname}
NAME=Localization
VERSION=1.0,REV=2008.03.05
CATEGORY=system
DESC=Localization Package
VENDOR="BeleniX"
EMAIL=
PKGSAV=/var/sadm/pkg/${PKGPREFIX}${pkgname}/save
MAXINST="1000"
SUNW_PRODNAME="SunOS"
SUNW_PRODVERS="5.11"
SUNW_PKGTYPE="root"
SUNW_PKGVERS="1.0"
HOTLINE="Please contact your local service provider"
__EOF__

	grep "i pkginfo" ${proto} > /dev/null
	[ $? -eq 0 ] || echo "i pkginfo" >> ${proto}
	grep "i copyright" ${proto} > /dev/null
	[ $? -eq 0 ] || echo "i copyright" >> ${proto}
	grep "i depend" ${proto} > /dev/null
	[ $? -eq 0 ] || echo "i depend" >> ${proto}

	rm -rf ${PKGPREFIX}${pkgname}
	pkgmk -o -f ${proto} -d ./ -r ${PROTODIR} -a i386
	if [ $? -ne 0 ]
	then
		echo "${PKGPREFIX}${pkgname}" >> failed
		fcnt=`expr $fcnt + 1`
	fi
	rm -f ${proto} ${proto}_com
done

echo "Failed packages: $fcnt"
) 2>&1 | tee mkpkgs.log
