#!/usr/bin/sh

swp=$1
cnt=0
fat=0
ext2fs=0
ntfs=0

for item in `echo q | /usr/sbin/format 2>&1 | egrep "c[0-9]+d[0-9]+" | nawk '{ print $2 }'`
do
	/usr/bin/prtpart /dev/rdsk/${item}p0 -ldevs > /tmp/prtpart.ldevs
	for d in `cat /tmp/prtpart.ldevs | grep -v "\.\.\." | nawk '{ print $1 }' | grep "/dev/dsk" | egrep -v "(p0$)|(p1$)|(p2$)|(p3$)|(p4$)"`
	do
		echo "$d" `/usr/bin/prtpart -t $d` | while read ldev dev st sz
		do
			lofi=`/usr/sbin/lofiadm -a "${dev}?segment=${st},${sz}"`
			if [ $? -eq 0 ]
			then
				ln -s $lofi $ldev
				ln -s `echo $lofi | sed 's|dev/lofi|dev/rlofi|'` \
					`echo $ldev | sed 's|dev/dsk|dev/rdsk|'`
			fi
		done
	done

	for fpart in `cat /tmp/prtpart.ldevs | grep -i fat | cut -f1`
	do
		/usr/bin/mkdir /mnt/fat$fat
		echo "$fpart -       /mnt/fat$fat   pcfs    -        no        -" >> /etc/vfstab
		fat=`expr $fat + 1`
	done

	for device in `cat /tmp/prtpart.ldevs  | grep "Linux native" | cut -f1`
	do
		typ=`/usr/lib/fs/ext2fs/fstyp $device`
		if [ "$typ" = "ext2fs" ]
		then
			/usr/bin/mkdir /mnt/linux$ext2fs
			echo "$device - /mnt/linux$ext2fs       ext2fs  -       no      -" >> /etc/vfstab
			ext2fs=`expr $ext2fs + 1`
		fi
	done

	for device in `cat /tmp/prtpart.ldevs | grep "IFS: NTFS" | cut -f1`
	do
		/usr/bin/mkdir /mnt/ntfs$ntfs
		echo "$device - /mnt/ntfs$ntfs  ntfs    -       no      -" >> /etc/vfstab
		ntfs=`expr $ntfs + 1`
	done

	if [ "x$swp" = "x0" ]
	then
		for device in `cat /tmp/prtpart.ldevs | grep "Linux swap" | cut -f1`
		do
			#
			# Add linux swap with swap area offfset at 10M from start
			#
			/usr/sbin/swap -a $device 20480
		done
	fi
done
