#!/sbin/sh
#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License, Version 1.0 only
# (the "License").  You may not use this file except in compliance
# with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Author: Moinak.Ghosh@Sun.COM


USAGE="Usage: $0 <method> [-- <X server arguments>]"

. /etc/profile.d/*.sh

DISPLAY="0"
DEFUSER=jack

METHOD=$1
if [ $# -lt 1 ] ; then
    echo $USAGE
    exit 2
fi
shift

case $METHOD in
    start)
	# Continue with rest of script
	;;
    *)
	echo "Invalid method $METHOD"
	exit 2
	;;
esac

if [ "$1" = "--" ] ; then
    shift
else
    if [ "$1" != "" ] ; then
	echo $USAGE
	exit 2
    fi
fi

if [ -f /.livecd ]
then
	if [ -f /.desk ]
	then
		desk=`cat /.desk`
	else
		desk="1"
	fi

	echo "Starting X11 (Keeping my fingers crossed!)" > /dev/console

	if [ "$desk" -eq "1" -o "$desk" -eq "3" ]
	then
		# Adjust wallpaper based on RAM size
		RAM=`/usr/bin/cat /.ram`
		if [ "$RAM" -le "256" ]
		then
			/usr/bin/cat /${DEFUSER}/.config/xfce4/mcs_settings/desktop.xml | sed s/belenix\-large\.jpg/belenix_wall4\.jpg/ > /${DEFUSER}/.config/xfce4/mcs_settings/desktop1.xml
			/usr/bin/mv /${DEFUSER}/.config/xfce4/mcs_settings/desktop1.xml /${DEFUSER}/.config/xfce4/mcs_settings/desktop.xml
		fi

		if [ "$desk" -eq "3" ]
		then
			echo "Auto-configuring X11 for Compiz ..." > /dev/console
			HOME=/root; export HOME
			/usr/X11/bin/Xorg -configure
			cp /root/xorg.conf.new /etc/X11/xorg.conf
			chmod 0666 /etc/X11/xorg.conf
			/usr/bin/modify-xorg-conf --with-experimental-ati-support
			if [ $? -eq 0 ]
			then
				su - ${DEFUSER} -c "/usr/sbin/startxfce compiz" &
			else
				echo "Compiz unsupported on this display ..."
				sleep 3
				su - ${DEFUSER} -c "/usr/sbin/startxfce normal" &
			fi
		else
			su - ${DEFUSER} -c "/usr/sbin/startxfce normal" &
		fi

	elif [ "$desk" -eq "2" -o "$desk" -eq "4" ]
	then
		if [ "$desk" -eq "4" ]
		then
			echo "Auto-configuring X11 for Compiz ..." > /dev/console
			HOME=/root; export HOME
			/usr/X11/bin/Xorg -configure
			cp /root/xorg.conf.new /etc/X11/xorg.conf
			chmod 0666 /etc/X11/xorg.conf
			/usr/bin/modify-xorg-conf --with-experimental-ati-support
			if [ $? -eq 0 ]
			then
				su - ${DEFUSER} -c "/usr/sbin/startkde compiz" &
			else
				echo "Compiz unsupported on this display ..." > /dev/console
				sleep 3
				su - ${DEFUSER} -c "/usr/sbin/startkde normal" &
			fi
		else
			su - ${DEFUSER} -c "/usr/sbin/startkde normal" &
		fi
	fi
else
	
	/usr/sbin/svcadm disable -t application/xserver
fi

sleep 1
exit 0
